apiVersion: v1
kind: Pod
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  containers:
    - name: goapp
      image: localhost:5000/go-app:tagVersion
      ports:
        - containerPort: 8080