apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: localhost:5000/go-app:tagVersion
      ports:
        - containerPort: 8080
